[package]
name = "exif_fixer"
version = "0.1.0"
authors = ["kalanamith <kalanamith@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kamadak-exif = "0.5.1"